#Лабораторная работа №1
Создание нейронной сети, выполняющей бинарную классификацию

##Теоретическая часть

In [1]:
import copy
import numpy as np
import random

Создадим цифры, из которых будет состоять наш датасет

In [2]:
numbers = list()
numbers.append(([0, 0],0))
numbers.append(([0, 1],1))
numbers.append(([1, 0],1))
numbers.append(([1, 1],1))

Сформируем датасет

In [3]:
dataset = list()
for i in range(10000):
  dataset.append(random.choice(numbers))

Выведем случайную цифру из датасета

In [4]:
random.choice(dataset)

([0, 0], 0)

Заполним единицами вектор весов связей между нейронами

In [5]:
first_layer_weights = np.ones((2, 1))

Создадим функцию активации, возвращающую единицу, если сумма полученных сигналов выше определенного порога

In [6]:
def result_bin_class(result):
  if (result > 1):
    return True
  else:
    return False

Создадим функцию подсчета суммарного веса полученных сигналов

In [7]:
def calculate_res(input_number, first_layer_weights):
  sum = 0
  for i in range(1):
    sum += input_number[0][i%2] * first_layer_weights[i]
  return sum

Зададим функцию, формирующую сигнал корректировки весов в зависимости от соотношения ответа нейронной сети и правильного ответа

In [8]:
def weight_changing(positive, target):
  k = 0
  if (positive and not target):
    k = -0.1
  elif (not positive and target):
    k = 0.1
  return k

Пропишем функции для обучения нейронной сети

In [9]:
def learn(input_number, first_layer_weights, target):
  k = weight_changing(result_bin_class(calculate_res(input_number, first_layer_weights)), True if input_number[1] == target else False)
  for i in range(1):
    first_layer_weights[i] += input_number[0][i%2] * k
  return first_layer_weights

In [10]:
def train_nn(input_dataset, first_layer_weights, target, size_of_data):
  for i in range(size_of_data):
    first_layer_weights = learn(random.choice(input_dataset), first_layer_weights, target)

In [11]:
train_nn(dataset, first_layer_weights, 1, 800)

In [13]:
first_layer_weights

array([[1.1],
       [1. ]])

Создадим функции для тестирования обученной нейронной сети

In [14]:
def test(input_number, first_layer_weights, target):
  if (result_bin_class(calculate_res(input_number, first_layer_weights)) == (True if input_number[1] == target else False)):
    return 1
  else:
    return 0

In [15]:
def test_nn(input_dataset, first_layer_weights, target, size_of_data):
  res = 0
  for i in range(size_of_data):
    res += test(random.choice(input_dataset), first_layer_weights, target)
  return (res / size_of_data)

In [16]:
print('Accuracy-score: ', test_nn(dataset, first_layer_weights, 1, 200))

Accuracy-score:  0.75


In [17]:
first_layer_weights = np.ones((2, 1))
train_nn(dataset, first_layer_weights, 5, 8000)

In [18]:
first_layer_weights

array([[1.],
       [1.]])

In [19]:
print('Accuracy-score: ', test_nn(dataset, first_layer_weights, 5, 2000))

Accuracy-score:  1.0


Попробуем создать зашумленный датасет и проверить как нейронная сеть справится с его обработкой

In [20]:
noise_dataset = list()
for i in range(10000):
  noise_dataset.append(random.choice(numbers))
  for j in range(1):
    noise_dataset[i][0][j%2] += (random.randint(-2, 2) * 0.1)

In [21]:
random.choice(noise_dataset)

([-8.799999999999994, 0], 0)

In [22]:
import copy
import random
noise_dataset = list()
for i in range(10000):
  noise_dataset.append(copy.deepcopy(random.choice(dataset)))
  for j in range(2):
    noise_dataset[i][0][j] += (random.randint(-45, 45) * 0.01)

In [23]:
random.choice(noise_dataset)

([2.5199999999999974, -0.35000000000000003], 1)

In [24]:
first_layer_weights = np.ones((2, 1))
train_nn(noise_dataset, first_layer_weights, 4, 8000)

In [25]:
train_nn(noise_dataset, first_layer_weights, 4, 8000)

In [26]:
first_layer_weights

array([[0.157],
       [1.   ]])

In [27]:
print('Accuracy-score: ', test_nn(noise_dataset, first_layer_weights, 4, 2000))

Accuracy-score:  1.0


Попробуем создать датасет с отсутствующей нормализацией некоторых значений

In [28]:
dataset_without_normalize = list()
for i in range(10000):
  dataset_without_normalize.append(copy.deepcopy(random.choice(numbers)))
  for j in range(2):
    dataset_without_normalize[i][0][j%2] += (random.randint(-45, 45) * 0.01)

In [29]:
print(random.choice(dataset_without_normalize))

([3.649999999999986, 0.77], 1)


In [30]:
first_layer_weights = np.ones((8, 1))
train_nn(dataset_without_normalize, first_layer_weights, 9, 8000)

In [31]:
train_nn(dataset_without_normalize, first_layer_weights, 9, 8000)

In [32]:
print('Accuracy-score: ', test_nn(dataset_without_normalize, first_layer_weights, 9, 2000))

Accuracy-score:  1.0


Для сравнения проведем такой же эксперимент для датасета с нормализацией

In [33]:
dataset_with_normalize = list()
for i in range(10000):
  dataset_with_normalize.append(copy.deepcopy(dataset_without_normalize[i]))
  #for j in [1, 5, 9]:
    #if dataset_with_normalize[i][0][j%2] != 0:
      #dataset_with_normalize[i][0][j%2] /= 255

In [34]:
print(random.choice(dataset_with_normalize))

([2.8299999999999974, 0.34], 1)


In [35]:
first_layer_weights = np.ones((15, 1))
train_nn(dataset_with_normalize, first_layer_weights, 9, 8000)

In [36]:
train_nn(dataset_with_normalize, first_layer_weights, 9, 8000)

In [37]:
print('Accuracy-score: ', test_nn(dataset_with_normalize, first_layer_weights, 9, 2000))

Accuracy-score:  1.0


##Практическая часть

In [ ]:
random.choice(noise_dataset)

([13.460000000000042, 34.000000000000064], 1)

**Задание (базовый уровень):**
Создать модель (без использования готовых решений) простейшего перцептрона, которая будет выполнять функцию логического "ИЛИ".

**Задание (повышенный уровень):**
Создать модель (без использования готовых решений) перцептрона, которая будет выполнять функцию исключающего "ИЛИ".

*Общее требование:*  Обучение и тестирование должно проходить на зашумленных данных (уровень шума +- 0.45).